// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type BookingFlight struct {
	ID                   int64         `json:"id"`
	BookingTransactionID sql.NullInt64 `json:"booking_transaction_id"`
	FlightID             sql.NullInt64 `json:"flight_id"`
	CurrencyCode         string        `json:"currency_code"`
	Price                float64       `json:"price"`
}

type BookingPassenger struct {
	ID                   int64          `json:"id"`
	BookingTransactionID sql.NullInt64  `json:"booking_transaction_id"`
	Title                sql.NullString `json:"title"`
	LastName             sql.NullString `json:"last_name"`
	FirstName            sql.NullString `json:"first_name"`
	DateOfBirth          sql.NullTime   `json:"date_of_birth"`
	TravelDocType        sql.NullString `json:"travel_doc_type"`
	TravelDocNumber      sql.NullString `json:"travel_doc_number"`
	FfpNumber            sql.NullString `json:"ffp_number"`
}

type BookingTransaction struct {
	ID              int64           `json:"id"`
	ReservationCode sql.NullString  `json:"reservation_code"`
	Status          sql.NullString  `json:"status"`
	ErrorCode       sql.NullInt32   `json:"error_code"`
	ErrorMessage    sql.NullString  `json:"error_message"`
	ContactEmail    string          `json:"contact_email"`
	ContactPhone    string          `json:"contact_phone"`
	CurrencyCode    sql.NullString  `json:"currency_code"`
	TotalPrice      sql.NullFloat64 `json:"total_price"`
	CreateDate      sql.NullTime    `json:"create_date"`
	ModifyDate      sql.NullTime    `json:"modify_date"`
}

type Flight struct {
	ID                     int64        `json:"id"`
	OriginAirportCode      string       `json:"origin_airport_code"`
	DestinationAirportCode string       `json:"destination_airport_code"`
	DepartureDateTime      time.Time    `json:"departure_date_time"`
	FlightNumber           string       `json:"flight_number"`
	BookingClass           string       `json:"booking_class"`
	FlightDuration         int32        `json:"flight_duration"`
	Enabled                bool         `json:"enabled"`
	SeatAvailable          int32        `json:"seat_available"`
	CurrencyCode           string       `json:"currency_code"`
	Price                  float64      `json:"price"`
	CreateDate             sql.NullTime `json:"create_date"`
	ModifyDate             sql.NullTime `json:"modify_date"`
}

type Role struct {
	ID         string         `json:"id"`
	Name       sql.NullString `json:"name"`
	Enabled    bool           `json:"enabled"`
	CreateDate sql.NullTime   `json:"create_date"`
	ModifyDate sql.NullTime   `json:"modify_date"`
}

type User struct {
	Email           string         `json:"email"`
	RoleID          sql.NullString `json:"role_id"`
	Title           sql.NullString `json:"title"`
	LastName        sql.NullString `json:"last_name"`
	FirstName       sql.NullString `json:"first_name"`
	DateOfBirth     sql.NullTime   `json:"date_of_birth"`
	Phone           sql.NullString `json:"phone"`
	TravelDocType   sql.NullString `json:"travel_doc_type"`
	TravelDocNumber sql.NullString `json:"travel_doc_number"`
	FfpNumber       sql.NullString `json:"ffp_number"`
	PasswordSalt    sql.NullString `json:"password_salt"`
	SecurePassword  sql.NullString `json:"secure_password"`
	Enabled         bool           `json:"enabled"`
	LastLoginDate   sql.NullTime   `json:"last_login_date"`
	CreateDate      sql.NullTime   `json:"create_date"`
	ModifyDate      sql.NullTime   `json:"modify_date"`
}
